// Code generated by "stringer -type=RtMsgType"; DO NOT EDIT.

package arp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GetExt-21]
}

const _RtMsgType_name = "GetExt"

var _RtMsgType_index = [...]uint8{0, 6}

func (i RtMsgType) String() string {
	i -= 21
	if i >= RtMsgType(len(_RtMsgType_index)-1) {
		return "RtMsgType(" + strconv.FormatInt(int64(i+21), 10) + ")"
	}
	return _RtMsgType_name[_RtMsgType_index[i]:_RtMsgType_index[i+1]]
}
